[project]
name = "anechoic-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lems-anechoic",
]

[tool.uv.sources]
lems-anechoic = { git = "https://github.com/msu-ssc/lems-anechoic", rev = "0.2.2" }
